apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-portal
  namespace: NAMESPACE_PLACEHOLDER
spec:
  replicas: REPLICAS_PLACEHOLDER
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: dm-portal
  template:
    metadata:
      labels:
        app: dm-portal
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: NotIn
                values:
                - arangodb
      containers:
      - name: dm-portal-image
        image: IMAGE_PLACEHOLDER
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
            limits:
              cpu: 800m
              memory: 1024Mi
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        env:
          - name: NODE_ENV
            value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: dm-portal-service
  namespace: NAMESPACE_PLACEHOLDER
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    selector:
      app: dm-portal
